### ISSUE TITLE
Bloomfilter Server pass to use json codification instead Gob one

### ISSUE THREAD

**Issue by froilson** [krakendio/krakend-documentation#169]
Hi, 

Could be possible to make use of net/rpc/jsonrpc to encode de response of bloomfilter server to revoke tokens so we can use a client in other languages other than Golang.

Or how can I use java to make a client compatibile with bloomfilter server?

Thanks

**Comment by alombarte** [comment]
This is not an actionable issue related to the documentation.

You can build the RPC client with any language you choose.
