### ISSUE TITLE
"sample_rate" incorrectly documented default value

### ISSUE THREAD

**Issue by Izzette** [krakendio/krakend-documentation#181]
Hi.  I'm currently evaluating KrakenD for use in our stack.  In testing the metrics and tracing integration with OpenCensus and the DataDog exporter, I was unable to enable tracing as documented.  Upon deeper investigation, it became clear that although the documentation [clearly states](https://github.com/krakendio/krakend-documentation/blob/373716bc7090db0ebb20a798faca3a5b136e474d/telemetry/opencensus.md?plain=1#L48) (in [two places](https://github.com/krakendio/krakend-schema/blob/6cec5cd138273bbf6a2141180bb4f29e98355ee5/telemetry/opencensus.json#L22)) that the default sample rate for `extra_config`->`telemetry/opencensus`->`sample_rate` is `100`, the default values is in-fact the Go zero-value for the type (integer) and as a result _does not sample any spans_.

I'm using [krakend-ce 882dd17](https://github.com/krakendio/krakend-ce/commit/882dd17bb18501ad7a397140fec6b61febd68ad7) (which is [just shy of v2.1.3](https://github.com/krakendio/krakend-ce/compare/882dd17bb18501ad7a397140fec6b61febd68ad7..v2.1.3)).

Tracing the path of the configuration, we see it is loaded by a patched version of viper which does not apply any defaults into a [`github.com/luraproject/lura/v2/config.ServiceConfig`](https://github.com/luraproject/lura/blob/cd9e4351648e81bf59e5c3ef0084089c09b4243d/config/config.go#L44).
* https://github.com/krakendio/krakend-ce/blob/882dd17bb18501ad7a397140fec6b61febd68ad7/cmd/krakend-ce/main.go#L49
* https://github.com/krakendio/krakend-viper/blob/master/parser.go

While [ServiceConfig.Init](https://github.com/luraproject/lura/blob/cd9e4351648e81bf59e5c3ef0084089c09b4243d/config/config.go#L343) is [called](https://github.com/krakendio/krakend-viper/blob/1a31848bfdbdb3ee86cf8ac241568aaff2087e99/parser.go#L37) and does provide default values to many structures, it does not provide any defaults for `ExtraConfig`/`"extra_config"`.
Now that the config is populated (without a default value for "sample_rate"), the [executor](https://github.com/krakendio/krakend-ce/blob/041858611d106bbae523256ff47beff408afd5d2/executor.go#L147) is called to register all the plugin components, including [metrics and tracing](https://github.com/krakendio/krakend-ce/blob/041858611d106bbae523256ff47beff408afd5d2/executor.go#L162).
When [registering metrics and traces](https://github.com/krakendio/krakend-opencensus/blob/a6ddd18cd6daef9dd997c1501bc20e51e972b605/opencensus.go#L38) from [MetricsAndTraces.Register](https://github.com/krakendio/krakend-ce/blob/041858611d106bbae523256ff47beff408afd5d2/executor.go#L360) <- [checkColaborators](https://github.com/krakendio/krakend-ce/blob/041858611d106bbae523256ff47beff408afd5d2/executor.go#L239), [SetDefaultSampler](https://github.com/krakendio/krakend-opencensus/blob/a6ddd18cd6daef9dd997c1501bc20e51e972b605/opencensus.go#L88) is called using the Go zero-value from `cfg` which will [`NeverSample`](https://github.com/krakendio/krakend-opencensus/blob/a6ddd18cd6daef9dd997c1501bc20e51e972b605/opencensus.go#L441-L442) the spans.

I can also confirm that setting the value to `100` will indeed result in tracing to work normally.

As I'm not sure whether this is an issue with the documentation or implementation, I'm cross-posting to krakend-ce.
Let me know if I can provide any more details.

**Comment by alombarte** [comment]
Thank you @Izzette for such a detailed issue.

The json-schema used to contain in the `default` the recommended value when you autocompleted a field in the editor, but at some point we changed it to express the actual default value that KrakenD reads when the value is missing. The opencensus missed that change. The documentation feeds itself from the krakend-schema, so the problem is carried twice.

I have adjusted the configuration to reflect the real values.

Thank you!
